"""rendre le champ numéro_commande nullable

Revision ID: 18af330f4bb5
Revises: 940834ed2e5a
Create Date: 2025-08-20 10:24:25.606426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18af330f4bb5'
down_revision = '940834ed2e5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commandes', schema=None) as batch_op:
        batch_op.alter_column('numero_commande',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commandes', schema=None) as batch_op:
        batch_op.alter_column('numero_commande',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
