"""Suppression de float des tables achats et approvisionnement

Revision ID: 7a58a9885f50
Revises: 51b85dadcef9
Create Date: 2025-08-25 09:32:31.639840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a58a9885f50'
down_revision = '51b85dadcef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achats', schema=None) as batch_op:
        batch_op.alter_column('prix_unitaire',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('montant_total',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('approvisionnements', schema=None) as batch_op:
        batch_op.alter_column('prix_unitaire',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('montant_total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('matieres_premieres', schema=None) as batch_op:
        batch_op.alter_column('prix_unitaire',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matieres_premieres', schema=None) as batch_op:
        batch_op.alter_column('prix_unitaire',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('approvisionnements', schema=None) as batch_op:
        batch_op.alter_column('montant_total',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('prix_unitaire',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('achats', schema=None) as batch_op:
        batch_op.alter_column('montant_total',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('prix_unitaire',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
