"""Initialisation complète

Revision ID: c04680dae641
Revises: 
Create Date: 2025-08-21 00:33:00.817064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c04680dae641'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fournisseurs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom_fournisseur', sa.String(length=200), nullable=False),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matieres_premieres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('categorie', sa.String(length=50), nullable=False),
    sa.Column('sous_categorie', sa.String(length=100), nullable=True),
    sa.Column('unite', sa.String(length=20), nullable=False),
    sa.Column('stock_actuel', sa.Integer(), nullable=False),
    sa.Column('stock_minimum', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('stock_minimum', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('achats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_achat', sa.Date(), nullable=False),
    sa.Column('fournisseur_id', sa.Integer(), nullable=False),
    sa.Column('matiere_id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Float(), nullable=False),
    sa.Column('prix_unitaire', sa.Float(), nullable=False),
    sa.Column('montant_total', sa.Float(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('date_livraison_prevue', sa.Date(), nullable=True),
    sa.Column('date_livraison_reelle', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['fournisseur_id'], ['fournisseurs.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres_premieres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approvisionnements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_achat', sa.DateTime(), nullable=False),
    sa.Column('fournisseur_id', sa.Integer(), nullable=False),
    sa.Column('matiere_id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('prix_unitaire', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('montant_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('date_livraison_prevue', sa.Date(), nullable=True),
    sa.Column('date_livraison_reelle', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fournisseur_id'], ['fournisseurs.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres_premieres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=True),
    sa.Column('nom', sa.String(length=100), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('code_postal', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commandes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_commande', sa.String(length=20), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('commercial_id', sa.Integer(), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_validation', sa.DateTime(), nullable=True),
    sa.Column('date_livraison_prevue', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('montant_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('montant_paye', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes_commercial', sa.Text(), nullable=True),
    sa.Column('motif_annulation', sa.Text(), nullable=True),
    sa.Column('commentaires_responsable', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['commercial_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_commande')
    )
    op.create_table('details_commandes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commande_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('prix_unitaire', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sous_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paiements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commande_id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mode_paiement', sa.String(length=50), nullable=False),
    sa.Column('date_paiement', sa.DateTime(), nullable=True),
    sa.Column('date_encaissement', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('validated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['validated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paiements')
    op.drop_table('details_commandes')
    op.drop_table('commandes')
    op.drop_table('clients')
    op.drop_table('users')
    op.drop_table('approvisionnements')
    op.drop_table('achats')
    op.drop_table('roles')
    op.drop_table('products')
    op.drop_table('matieres_premieres')
    op.drop_table('fournisseurs')
    # ### end Alembic commands ###
