"""ajout de champs pou la gestion  du stock aprés validation par le responsable

Revision ID: d27262ee694a
Revises: 7a58a9885f50
Create Date: 2025-08-26 10:38:43.117163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd27262ee694a'
down_revision = '7a58a9885f50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commandes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_annulation', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('commentaires_validation', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commandes', schema=None) as batch_op:
        batch_op.drop_column('commentaires_validation')
        batch_op.drop_column('date_annulation')

    # ### end Alembic commands ###
