"""Ajout du champ prix_unitaire à MatierePremiere

Revision ID: fe1b27453a4b
Revises: c04680dae641
Create Date: 2025-08-21 00:54:37.207812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe1b27453a4b'
down_revision = 'c04680dae641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matieres_premieres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prix_unitaire', sa.Float(), nullable=False, server_default='0.0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matieres_premieres', schema=None) as batch_op:
        batch_op.drop_column('prix_unitaire')

    # ### end Alembic commands ###
